services:
  tenv:
    build:
      context: .
      args:
        DOCKER_BASE_IMAGE: ${DOCKER_BASE_IMAGE:?err}
        TENV_VERSION: ${TENV_VERSION:?err}
        TFLINT_VERSION: ${TFLINT_VERSION:?err}
        TRIVY_VERSION: ${TRIVY_VERSION:?err}
        GUARD_VERSION: ${GUARD_VERSION:?err}
    image: futureys/tenv:development
    volumes:
      - .:/workspace:cached
      - /workspace/.venv
      - ~/.aws:/root/.aws
      - ~/.claude:/root/.claude
