services:
  tenv:
    build:
      context: .
      args:
        # - futureys/claude-code-python-development - Docker Image
        #   https://hub.docker.com/r/futureys/claude-code-python-development/tags
        DOCKER_BASE_IMAGE: futureys/claude-code-python-development:20260710125000
        # - Releases · tofuutils/tenv
        #   https://github.com/tofuutils/tenv/releases
        TENV_VERSION: v4.14.8
        # - Releases · terraform-linters/tflint
        #   https://github.com/terraform-linters/tflint/releases
        TFLINT_VERSION: v0.64.0
        # - Releases · aquasecurity/trivy
        #   https://github.com/aquasecurity/trivy/releases
        TRIVY_VERSION: v0.72.0
        # - Releases · aws-cloudformation/cloudformation-guard
        #   https://github.com/aws-cloudformation/cloudformation-guard/releases
        GUARD_VERSION: 2.1.4
    image: futureys/tenv:development
    volumes:
      - .:/workspace:cached
      - /workspace/.venv
      - ~/.aws:/root/.aws
      - ~/.claude:/root/.claude
